version: '3.8'

services:
 web:
  build: app
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  
  frontend:
    build: frontend
    ports: 
      - 8080:80
 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=password
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: